### ISSUE TITLE
friend help me get this error when I run ionic serve in step 2.18

### ISSUE THREAD

**Issue by BrandonLeck** [Urigo/IonicCLI-Meteor-WhatsApp#1]
ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'lib/angular/angular' in C:\Develop\developIonic\ionic-meteor-whatsapp\src
 @ ./src/index.js 5:0-37

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'lib/angular-animate/angular-animate' in C:\Develop\developIonic\ionic-meteor-whatsapp\src
 @ ./src/index.js 7:0-53

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'lib/angular-sanitize/angular-sanitize' in C:\Develop\developIonic\ionic-meteor-whatsapp\src
 @ ./src/index.js 9:0-55

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'lib/angular-ui-router/release/angular-ui-router' in C:\Develop\developIonic\ionic-meteor-whatsapp\src
 @ ./src/index.js 11:0-65

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'lib/ionic/js/ionic' in C:\Develop\developIonic\ionic-meteor-whatsapp\src
 @ ./src/index.js 13:0-36

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'lib/ionic/js/ionic-angular' in C:\Develop\developIonic\ionic-meteor-whatsapp\src
 @ ./src/index.js 15:0-44

**Comment by DAB0mB** [comment]
Make sure your webpack config is set as seen in step 1. Did you do it? It seems like a problem with the alias to the 'lib' dir.

**Comment by rmyndharis** [comment]
there are slightly change on webpack by the way.
To fix it, you can move 'alias' into resolve in module.export of webpack.config.js

The complete code like follow:

```
var camelCase = require('lodash.camelcase');
var upperFirst = require('lodash.upperfirst');

module.exports = {
  entry: [
    './src/index.js'
  ],
  output: {
    path: __dirname + '/www/js',
    filename: 'app.bundle.js'
  },
  externals: [{
      'angular': 'angular',
      'cordova': 'cordova',
      'ionic': 'ionic'
    },
    resolveExternals
  ],
  target: 'web',
  devtool: 'source-map',
  babel: {
    presets: ['es2015', 'stage-0'],
    plugins: ['add-module-exports']
  },
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /(node_modules|www)/,
      loader: 'babel'
    }]
  },
  resolve: {
    alias: {
      lib: __dirname + '/www/lib'
    },
    extensions: ['', '.js']
  }
};

function resolveExternals(context, request, callback) {
  return cordovaPlugin(request, callback) ||
    callback();
}

function cordovaPlugin(request, callback) {
  var match = request.match(/^cordova\/(.+)$/);
  var plugin = match && match[1];

  if (plugin) {
    plugin = camelCase(plugin);
    plugin = upperFirst(plugin);
    callback(null, 'this.cordova && cordova.plugins && cordova.plugins.' + plugin);
    return true;
  }
}
```

**Comment by DAB0mB** [comment]
@armyndharis Yes I can see that, thank you from bringing this to my attention. I changed it back in one of the next steps, so I probably didn't notice.

**Comment by DAB0mB** [comment]
OK. So as you can probably see I debased my master and the tutorial should be updated and deployed soon :-) Until then I will leave this issue open.

**Comment by rmyndharis** [comment]
Thank you @DAB0mB .. :)

**Comment by BrandonLeck** [comment]
@armyndharis and @DAB0mB thanks his help was invaluable. The code already worked.
