### ISSUE TITLE
ln: failed to create symbolic link: File name too long

### ISSUE THREAD

**Issue by BrandonLeck** [Urigo/IonicCLI-Meteor-WhatsApp#4]
Friends I have this problem when I try to create a symbolic link to the node_modules folder inside some units folders with long names are.

$ ln -s ../node_modules
ln: failed to create symbolic link './node_modules' -> '../node_modules': File name too long

Is there a problem if I miss this?

**Comment by DAB0mB** [comment]
@BrandonLeck Did you manage to solve your issue? I'm not experiencing anything similar.

**Comment by deep0892** [comment]
how to run this project, any help please ??

**Comment by lamjack** [comment]
```bash
$ git clone https://github.com/xxx/xxx.git
$ cd xxx
$ git config --list
$ git config core.symlinks false
$ git checkout master
```
reference: https://lamjack.github.io/2017/04/20/git-failed-to-create-symbolic-link-for-mac/
