### ISSUE TITLE
Problems with the account authentication

### ISSUE THREAD

**Issue by Like-Jean** [Urigo/IonicCLI-Meteor-WhatsApp#6]
Hello friends, I got trouble with account authentication that it shows Account.user() is not a function on my browser. And my bower.json file seems ok with all the dependencies for account authentication:
{
  "name": "HelloIonic",
  "private": "true",
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.3.1"
  },
  "dependencies": {
    "angular-meteor": "^1.3.11",
    "meteor-client-side": "^1.3.1",
    "angular-moment": "^0.10.3",
    "accounts-phone": "^0.0.21",
    "angular-meteor-auth": "^1.0.3"
  }
}

So is that something wrong with the version of accounts-phone or angular-meteor?

**Comment by DAB0mB** [comment]
First, before you use the `Accounts` object make sure you import it like so:

``` js
import {Accounts} from 'meteor/accounts-base';
```

Note the the method `Accounts.user()` may not be available in older versions of `accounts-base`. Make sure you use the latest version of it, otherwise you gonna have to access it using `Meteor.user()`.

**Comment by Like-Jean** [comment]
Thank you for your patient answer. But I checked that my **accounts-base** version and found it is 1.2.8 and I checked your project's is 1.2.7 . Actually, I tried to run the complete project that cloned from your repository, but got the same problem. So I guess it is something wrong with my local settings...

**Comment by DAB0mB** [comment]
@Like-Jean This problem is fixed and deployed on master, the use of bower is deprecated so instead we use npm with some fixed version of `angular-meteor` and `angular-meteor-auth`
